import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.scss";

import Link from "next/link";
import CardArticles from "@/components/CardArticles";
import { useRouter } from "next/router";
import AsideNav from "@/components/AsideNav";
const path = require("path");
//appel api
export async function getStaticProps() {
  const data2 = fetch("https://jsonplaceholder.typicode.com/posts");
  const articles = await (await data2).json();
  return {
    props: {
      articles,
    },
  };
}

export default function Home(props) {
  console.log("******************");
  console.log(props.articles[0].title);
  console.log("******************");
  const commentaires = props.articles[0].body;

  console.log(commentaires);
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Blog Thierry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/**  {props.articles.map((article) => (
          <li key={article.id}>{article.title}</li>
        ))} */}
        <div className={styles.index_container_h1}>
          <h1>Bienvenu sur EICERAMIQUE </h1>
          {/** <p>Router ={router.asPath}</p>*/}
        </div>
        <section className={styles.home_section_container}>
          <Link href={"/articles"}>
            <CardArticles
              title="Les articles"
              description={"Nos articles sur la céramique"}
              commentaire={commentaires + "..."}
            />
          </Link>
          <Link href={"/articles/atelier"}>
            <CardArticles
              title="Les ateliers"
              description={props.articles[1].title}
              commentaire={props.articles[1].body + "..."}
            />
          </Link>
          <Link href={"/articles/four"}>
            <CardArticles
              title="Les Fours"
              description={"Les réparations et les fours innovants"}
              commentaire={
                "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,bonjour a vous bande  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi "
              }
            />
          </Link>
          <Link href={"/articles/tour"}>
            <CardArticles
              title="Les Tours"
              description={"Les tours Models ?"}
              commentaire={
                "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,bonjour a vous bande  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi "
              }
            />
          </Link>
          <Link href={"/articles/tournage"}>
            <CardArticles
              title="Le tournage"
              description={"Videos et autre astuces"}
              commentaire={
                "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,bonjour a vous bande  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi "
              }
            />
          </Link>
          <Link href={"/articles/nouveauarticle"}>
            <CardArticles
              title="nouveaux articles"
              description={"Les derniers articles à voir"}
              commentaire={
                "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt,bonjour a vous bande  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi  ullam optio, facere corporis natus at, repellendus quam repudiandae nisi "
              }
            />
          </Link>
        </section>
        <AsideNav />
      </main>
    </>
  );
}
